-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION pg_net;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE TABLE public.databaseversion (
  version character varying(20) NOT NULL
);

ALTER TABLE public.databaseversion
  ADD CONSTRAINT databaseversion_pkey PRIMARY KEY (VERSION);

GRANT ALL ON public.databaseversion TO anon;

GRANT ALL ON public.databaseversion TO authenticated;

GRANT ALL ON public.databaseversion TO service_role;

CREATE TABLE public.roles (
  roleid      integer               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rolename    character varying(10) NOT NULL,
  description character varying(50)
);

ALTER TABLE public.roles
  ADD CONSTRAINT roles_pkey PRIMARY KEY (roleid);

GRANT ALL ON public.roles TO anon;

GRANT ALL ON public.roles TO authenticated;

GRANT ALL ON public.roles TO service_role;

CREATE TABLE public.users (
  userid     uuid                        NOT NULL,
  username   character varying(20),
  password   text,
  firstname  character varying(20),
  lastname   character varying(20),
  roleid     integer,
  created_at timestamp without time zone
);

ALTER TABLE public.users
  ADD CONSTRAINT rolefk FOREIGN KEY (roleid) REFERENCES public.roles(roleid);

ALTER TABLE public.users
  ADD CONSTRAINT users_pkey PRIMARY KEY (userid);

GRANT ALL ON public.users TO anon;

GRANT ALL ON public.users TO authenticated;

GRANT ALL ON public.users TO service_role;
